### ISSUE TITLE
test.sh fails 

### ISSUE THREAD

**Issue by davidmlw** [sifive/api-firrtl-sifive#6] opened 2019-07-11 20:43 UTC
I met firrtl build failure, so I do this test.sh, and found similar error. 

Is this an error of Firrtl source code or an error of my environment?
```
[~/w/e/a/test-ws] : which protoc                                                                                       {9fbfcf1}
/usr/bin/protoc
[~/w/e/a/test-ws] : wake 'source "firrtl/regress/ICache.fir" | makeFirrtlCompilePlan firrtlScalaModule.scalaModuleClasspath "test" "build" | runFirrtlCompile | getFirrtlCompileOutputsTargetOutputs'
<ivycache> ivycache
api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloop/firrtl.json -b
scala --coursier-cache ivycache --bloop-args compile -c build/api-scala-sifive/bloop firrtl --jar build/firrtl/scala-2.12/jar/firrtl.jar
[E] [E7] ../../firrtl/src/main/scala/firrtl/proto/FromProto.scala:293:22
[E]      value hasExternalModule is not a member of firrtl.FirrtlProtos.Firrtl.Module
[E]      L293:       require(module.hasExternalModule, "Module must have Module or ExtModule")
[E]                                 ^
[E] [E6] ../../firrtl/src/main/scala/firrtl/proto/FromProto.scala:291:16
[E]      value hasUserModule is not a member of firrtl.FirrtlProtos.Firrtl.Module
[E]      L291:     if (module.hasUserModule) convert(module.getUserModule)
[E]                           ^
[E] ../../firrtl/src/main/scala/firrtl/Driver.scala: L20 [E1], L20 [E2]
[E] ../../firrtl/src/main/scala/firrtl/RenameMap.scala: L70 [E3], L71 [E4], L72 [E5]
[E] ../../firrtl/src/main/scala/firrtl/proto/FromProto.scala: L291 [E6], L293 [E7]
[E] 'firrtl' failed to compile.
Scala compilation failed for 'api-scala-sifive/bloop_wake -t build/api-scala-sifive/bloop/firrtl.json.template -c build/api-scala-sifive/bloop/firrtl.json -b scala --coursier-cache ivycache --bloop-args "compile -c build/api-scala-sifive/bloop firrtl" --jar build/firrtl/scala-2.12/jar/firrtl.jar'
Nil
```

**Comment by jackkoenig** [comment] 2019-07-15 23:30
We spoke offline, but this is an issue where FIRRTL requires protoc > 3.0.0 (I'm not certain what the minimum version is). This project currently uses the runtime for protoc 3.5.0 [1], so I generally suggest using protoc around that version (I have confirmed that 3.6.1 works, but 3.8.0 does NOT work).

I think we need a better way to handle this, but it's a bit complicated because FIRRTL needs the Java runtime and that needs to be relatively in sync with the version of protoc installed on the system.

[1] https://github.com/sifive/api-firrtl-sifive/blob/9fbfcf19ae795c82aa41caec603bf442ff7cc7a5/ivydependencies.json#L12

**Comment by jackkoenig** [comment] 2019-07-15 23:30
I would like a better way to deal with protobuf, but for now I'm going to close this issue.

**Closed by jackkoenig** 2019-07-15 23:30 UTC

**Comment by saurabhsingh-pvips** [comment] 2019-11-19 07:17
I encountered the same issue with protoc `v3.11.0` recently.
